# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f05608954e85f139b09e1f50ba49c00a7ce9e64aee5956e4e2ba75970f73ab298d2ed34f4a49d43ad02287977de24eaafe90a816a1561ef5127c67fa7e244d

test:
  secret_key_base: 331b67b8cb9d701c501110047c40cb93aaebec772034dbf473436ddefc8c6d0742dbea694279ae46b5d55f5193804f7168bc117bd716e2f1450e21eab7b20e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
